language: objective-c
os: osx
osx_image: xcode9.2
xcode_project: MountView.xcodeproj
xcode_scheme: MountView
script: xcodebuild clean && xcodebuild build -project MountView.xcodeproj -scheme MountView
